Calculator
AUF42/JuliaFrolova_LevelUp pull request #1
Opened 2020-05-04 21:38 UTC by AUF42

task is comleted

2020-05-12 21:09 UTC, khda91 requested changes
1. Очистить репозиторий от файлов среды разработки
2. уйти от использования static

2020-05-12 21:09 UTC, khda91 commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Почему файл из папки `.idea` присутствует в репозитории кода?

2020-05-12 21:09 UTC, khda91 commented on .idea/jarRepositories.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Почему файл из папки `.idea` присутствует в репозитории кода?

2020-05-12 21:09 UTC, khda91 commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Почему файл из папки `.idea` присутствует в репозитории кода?

2020-05-12 21:09 UTC, khda91 commented on homework_1.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Почему файл `iml` присутствует в репозитории кода?

2020-05-12 21:09 UTC, khda91 commented on src/main/java/homework_1/Difference.java
> +    public static int calculateDiff(int number1,int number2) {
Почему метод `static`?

2020-05-13 19:37 UTC, AUF42 commented
> 1. Очистить репозиторий от файлов среды разработки
> 2. уйти от использования static

Исправлено

2020-05-14 08:33 UTC, khda91 approved these changes
Работа принята

2020-05-28 22:58 UTC, merged