Homework 2
AUF42/JuliaFrolova_LevelUp pull request #2
Opened 2020-05-10 10:52 UTC by AUF42

homework_2 is completed

2020-05-10 11:00 UTC, AUF42 commented
wrong commit

2020-05-10 11:03 UTC, AUF42 commented
finally MR is corrected and HM is finished

2020-05-12 23:02 UTC, khda91 requested changes
Удалить файлы ide из репозитория

2020-05-12 23:02 UTC, khda91 commented on .idea/.gitignore
> +# Default ignored files
Файлов `ide` не должно быть в репозитории

2020-05-13 17:35 UTC, AUF42 commented on .idea/.gitignore
> +# Default ignored files
исправлено

2020-05-14 08:34 UTC, khda91 approved these changes
Работа принята

2020-06-03 00:24 UTC, merged