Homework 3
AUF42/JuliaFrolova_LevelUp pull request #3
Opened 2020-05-11 11:42 UTC by AUF42

2020-05-15 10:01 UTC, khda91 requested changes

2020-05-15 10:01 UTC, khda91 commented on pom.xml
> +    <dependencies>
Проект не собирается :)

2020-05-17 10:51 UTC, AUF42 commented on pom.xml
> +    <dependencies>
Исправила замечания: добавила jar в структуру проекта (вместо подключенной библиотеки), и привела состояние классов в соответствие с Java Conventions

2020-05-21 23:14 UTC, khda91 approved these changes
Работа принята

2020-06-03 00:27 UTC, merged